name: B by Akshay A Baliga
favicon: null
layout_spectrum: 0.61782
typography_spectrum: 0.89955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#272727'
    - '#a3a3a3'
    - '#9e0404'
  brandStrength: 0.75
  lightness: 0.0625
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
